server:
  port: 8080

camel:
  springboot:
    main-run-controller: true

api:
  groups:
    test:
      sources:
        user-from-postgres:
          type: db
          config:
            url: jdbc:postgresql://localhost:5432/postgres
            username: postgres
            password: postgres
            database: postgres
          path: $
          query: SELECT * FROM users

        user-from-oracle:
          type: db
          config:
            url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
            username: system
            password: oracle
            database: oracle
          path: $
          query: SELECT * FROM users

    demo:
      sources:
        user-full-data:
          type: rest
          url: https://dummyjson.com/users/{id}
          path: $

        user-with-dto:
          type: rest
          url: https://dummyjson.com/users/{id}
          path: $
          fields:
            id: $.id
            firstName: $.firstName
            lastName: $.lastName
            age: $.age
            gender: $.gender
            mailAddress: $.email
            phoneNumber: $.phone
            userName: $.username
            height: $.height
            weight: $.weight
            hairColor: $.hair.color
            country: $.address.country

        user-company-info:
          type: rest
          url: https://dummyjson.com/users/{id}
          path: $.company

        user-cart:
          type: rest
          url: https://dummyjson.com/carts/user/{id}
          path: $.carts[?(@.total > 1500)]
          #Test 1500 v√† 2000

        continents-soap:
          type: soap
          url: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso
          path: $.Body.ListOfContinentsByNameResponse.ListOfContinentsByNameResult.tContinent
          soapAction: ListOfContinentsByName
          fields: # DTO Work with list
            code: $.sCode
            name: $.sName



